### ISSUE TITLE
[tracking ticket] docs update

### ISSUE THREAD

**Issue by heyjay44** [fireproof-storage/fp-website#42]
Eric:
- [ ] update messaging on welcome page: https://use-fireproof.com/docs/welcome/
     - [ ] Consider removing code snippets since that reads like a quickstart
- [ ] how do we want the concept guide to fit into the narrative: https://use-fireproof.com/docs/category/concept-guide

Marty:
1. update technical details on: 
- [ ] P0: quickstart: https://use-fireproof.com/docs/getting-started
- [ ] P0: react tutorial: https://use-fireproof.com/docs/react-tutorial
- [ ] P1: https://use-fireproof.com/docs/solid-tutorial (or consider removing for now, there is a lot of surface area to the docs)
